# Generated by Django 2.2.2 on 2019-06-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('fullname', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('profileImage', models.URLField(verbose_name='Profile image URL')),
                ('lastAccess', models.DateTimeField(verbose_name='Last access')),
            ],
        ),
    ]
