# Generated by Django 2.2.2 on 2019-06-03 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheChatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='lastAccess',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 20, 19, 31, 232123), verbose_name='Last access'),
        ),
    ]
