# Generated by Django 2.2.2 on 2019-06-03 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CheChatApp', '0002_auto_20190603_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='lastAccess',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last access'),
        ),
    ]
